/** 统一题型协议（对齐产品文档 3.2.1）与一期领域模型 */

export type QuestionSource = "resume" | "job_search" | "jd_target" | "mock_interview";

export type QuestionType =
  | "single_choice"
  | "multi_choice"
  | "judge"
  | "short_answer"
  | "scenario";

/** 错因三分法 */
export type WrongReason = "concept" | "misread" | "blind_spot";

export const WRONG_REASON_LABEL: Record<WrongReason, string> = {
  concept: "概念不清",
  misread: "审题失误",
  blind_spot: "知识盲区",
};

export const SOURCE_LABEL: Record<QuestionSource, string> = {
  resume: "简历生成",
  job_search: "岗位检索",
  jd_target: "JD定制",
  mock_interview: "模拟面试",
};

export interface UserProfile {
  name: string;
  avatarText: string;
  targetRole: string;
  years: number;
  streak: number;
  totalAnswered: number;
  correctRate: number;
  /** 脱敏手机号（138****6021），仅我的页展示 */
  phone?: string;
  wechatBound?: boolean;
}

/** 一期只开放复习提醒；学习报告 / 通知管理 / 数据导出随承载功能落二期 */
export interface UserSettings {
  reviewReminderEnabled: boolean;
  /** HH:mm，24 小时制 */
  reviewReminderTime: string;
}

export type DeactivationStatus = "cooling_off" | "executed";

export interface DeactivationInfo {
  status: DeactivationStatus;
  requestedAt: string;
  coolingOffUntil: string;
  remainingDays: number;
  reason: string;
  /** 注销会删除的数据范围（申请前向用户明示） */
  scopes: string[];
  revocable: boolean;
}

/** 我的页一次拉齐：资料 + 三统计卡 + 扩展计数 + 偏好 + 注销态 */
export interface MeProfile {
  profile: UserProfile;
  settings: UserSettings;
  stats: {
    answered: number;
    correctRate: number;
    streak: number;
    pendingReview: number;
    mastered: number;
  };
  counts: {
    sets: number;
    favorites: number;
    questions: number;
  };
  deactivation: DeactivationInfo | null;
}

export interface ProfileUpdate {
  name?: string;
  avatarText?: string;
  targetRole?: string;
  years?: number;
}

export interface DeletionResult {
  ok: boolean;
  executedAt: string;
  /** 各类数据实际清理条数 */
  deleted: Record<string, number>;
  detail: string;
}

export interface PlanTask {
  id: string;
  type: "practice" | "review" | "interview" | "jd_set" | "resume_check";
  title: string;
  estMinutes: number;
  done: boolean;
  /** AI/规则生成（手动添加为 false，不展示徽标） */
  autoGenerated: boolean;
  /** practice 任务对应题集 id，其余 null */
  refId: string | null;
}

/** GET /api/plans 一次拉齐：任务 + 完成度 + streak 横幅（二期） */
export interface PlanList {
  items: PlanTask[];
  doneCount: number;
  total: number;
  streak: number;
  /** 今日是否已打卡（完成 ≥ 2/3） */
  checkedIn: boolean;
  /** saved=当日已存 / ai=AI 生成 / rule=规则兜底 / manual=手动变更 / checked_in=本次达成打卡 */
  source: string;
}

/** 本周图表 + 三卡（/api/stats/week，从作答事件真实聚合） */
export interface WeekOverview {
  bars: { day: string; value: number; date: string }[];
  stats: { answered: number; correctRate: number; pendingReview: number };
}

/** 学习周报（/api/reports/weekly，二期） */
export interface WeeklyReport {
  weekKey: string;
  /** 近 7 天逐日：date / answered / correctRate（无作答日为 null） */
  trend: { date: string; answered: number; correctRate: number | null }[];
  answered: number;
  correctRate: number;
  masteredTotal: number;
  weakPoints: { tag: string; wrongCount: number }[];
  suggestion: string;
}

/* ---------------- 模拟考试（二期批 2，P11） ---------------- */

/** 考试态题目：不携带答案/解析（判分只在后端） */
export interface ExamQuestion {
  id: string;
  setId: string;
  type: QuestionType;
  category: string;
  stem: string;
  options: string[];
  knowledgeTags: string[];
  difficulty: 1 | 2 | 3;
}

/** POST /api/exams：组卷结果 */
export interface ExamPaper {
  examId: string;
  total: number;
  /** 限时 = 题数 × 90 秒 */
  durationSec: number;
  questions: ExamQuestion[];
}

/** GET /api/exams：历史列表（含 running，入口据此弹恢复） */
export interface ExamListItem {
  examId: string;
  setId: string;
  bucketRole: string;
  total: number;
  answered: number;
  score: number | null;
  durationSec: number;
  status: "running" | "paused" | "done" | "abandoned";
  createdAt: string;
  finishedAt: string | null;
}

/** GET /api/exams/{id}：考试现场（running/paused 原样返回） */
export interface ExamState {
  examId: string;
  setId: string;
  bucketRole: string;
  total: number;
  answered: number;
  score: number | null;
  status: ExamListItem["status"];
  /** 后端算好的已用有效时长（不含暂停） */
  elapsedSec: number;
  durationSec: number;
  createdAt: string;
  finishedAt: string | null;
  questions: ExamQuestion[];
  answers: Record<string, { choice: string; timeSec: number }>;
  /** 时间已到（前端引导交卷） */
  expired?: boolean;
}

/** GET /api/exams/{id}/report：模考报告（P11） */
export interface ExamReport {
  examId: string;
  bucketRole: string;
  score: number;
  total: number;
  answered: number;
  correct: number;
  correctRate: number;
  durationSec: number;
  pausedSec: number;
  finishedAt: string | null;
  dimensionScores: { label: string; correct: number; total: number; score: number }[];
  /** 同岗位分桶百分位；样本 <5 为 null（前端显示「样本积累中」） */
  percentile: number | null;
  sampleSize: number;
  weakPoints: { tag: string; wrongCount: number }[];
  history: { examId: string; score: number | null; finishedAt: string | null }[];
}

/** POST /api/exams/{id}/remedial：补强练习卷题集 */
export interface RemedialResult {
  setId: string;
  title: string;
  questionCount: number;
}

export interface QuestionSet {
  id: string;
  source: QuestionSource;
  /** 归属用户：空=预置公共题库（所有人可见、不可删）；非空=本人私有题集 */
  ownerId?: string;
  title: string;
  questionCount: number;
  updatedAt: string; // 真实更新时间（YYYY-MM-DD HH:MM）
}

export interface Question {
  id: string;
  setId: string;
  type: QuestionType;
  category: string;
  stem: string;
  options: string[]; // 客观题选项
  answer: string; // 如 "B"
  referenceAnswer: string;
  explanation: string;
  knowledgeTags: string[];
  difficulty: 1 | 2 | 3;
  /** 全站答对率（0~100），低样本（<100 次作答）为 null 不展示 */
  siteCorrectRate: number | null;
}

export interface WrongItem {
  questionId: string;
  setId: string;
  reason: WrongReason;
  wrongCount: number;
  lastWrongAt: string; // 展示文案，如「昨天」
  /** 艾宾浩斯阶段索引 0~4 对应 1/2/4/7/15 天 */
  stage: number;
  nextReviewLabel: string; // 展示文案，如「今天」「第 4 天」
  mastered: boolean;
  /** 复习连续答对次数，满 3 提前毕业 */
  reviewStreak: number;
}

/** 简历体检报告（批 3，后端 analyzer 一次解析多路消费产出） */
export interface ResumeCheckup {
  totalScore: number;
  comment: string;
  highlights: string[];
  improvements: string[];
  suggestions: string[];
}

export interface ResumeAnalysis {
  resumeId?: string;
  fileName: string;
  years: number;
  targetRole: string;
  estimatedCount: number;
  dimensions: { label: string; score: number }[];
  checkup?: ResumeCheckup | null;
}

/** GET /api/resumes：简历版本行（version 降序；旧记录可能缺 checkup，体检接口惰性补算） */
export interface ResumeVersion {
  resumeId: string;
  version: number;
  isOptimized: boolean;
  fileName: string;
  createdAt: string;
  analysis: ResumeAnalysis | null;
}

/** 站内通知（批 4；type: generate_done / exam_report / review_due / interview_prep） */
export interface NotificationItem {
  id: string;
  type: string;
  payload: {
    examId?: string;
    score?: number;
    generated?: number;
    count?: number;
    setId?: string;
    /** interview_prep（四期）：面试岗位名 / 面试日期 / 看板卡 id */
    jobName?: string;
    interviewAt?: string;
    cardId?: string;
  } | null;
  read: boolean;
  createdAt: string;
}

export interface GenerateProgress {
  generated: number;
  total: number;
  currentDimension: string;
  done: boolean;
  /** 被结构校验 / 答案二次校验 / 去重淘汰的题量 */
  dropped?: number;
  /** 非空表示任务失败（部分或全部批次），直接展示给用户 */
  error?: string | null;
  /** 本次生成落库的题集 id，完成后可跳转 */
  setId?: string | null;
  /** 任务 id（active 恢复接口 / 进度回传统一携带） */
  taskId?: string;
  /** 服务重启导致的中断任务：提示「继续补齐剩余题目」而非报错 */
  interrupted?: boolean;
}

/** 当前用户最近的未完成出题任务（GET /api/question-sets/generate/active） */
export type ActiveGenerateTask = { taskId: string | null } & Partial<GenerateProgress>;

/* ---------------- 管理端：模型配置（产品文档 4.6.1） ---------------- */

/** 四类分层模型 + 语音，对应架构图 LLM 层 */
export type LlmLayer = "primary" | "light" | "vision" | "embedding" | "voice";

export interface LlmConfig {
  layer: LlmLayer;
  label: string;
  usage: string;
  provider: string;
  modelName: string;
  /** 仅掩码（sk-****abcd），接口永不返回明文 */
  apiKeyMasked: string;
  hasKey: boolean;
  baseUrl: string;
  params: Record<string, number | string>;
  fallbackModel: string;
  enabled: boolean;
  updatedAt: string;
  updatedBy: string;
}

export interface LlmConfigUpdate {
  provider?: string;
  modelName?: string;
  /** 留空或回传掩码 = 不修改 */
  apiKey?: string;
  baseUrl?: string;
  params?: Record<string, number | string>;
  fallbackModel?: string;
  enabled?: boolean;
}

export interface LlmTestResult {
  ok: boolean;
  latencyMs?: number;
  tokens?: number;
  error?: string;
  /** 成功时的补充信息（如本地推理维度 / 相似度校验） */
  detail?: string;
}

/** 供应商：选定即自动回填 baseUrl（可手改），capabilities 决定能承接哪些分层 */
export interface LlmProvider {
  id: string;
  label: string;
  /** cloud=云端 API / selfhost=本机自托管 / local=项目内置权重 / custom=自定义网关 */
  kind: "cloud" | "selfhost" | "local" | "custom";
  baseUrl: string;
  requiresKey: boolean;
  keyPlaceholder: string;
  /** 获取 API Key 的官方文档链接（缺省=不展示）；voice 层锁定 qwen 时在 Key 下方给出 */
  keyUrl?: string;
  capabilities: LlmLayer[];
  hint: string;
}

export interface ModelOption {
  id: string;
  label?: string;
  ownedBy?: string;
  kind?: string;
}

/** 模型发现结果：source=remote 实时拉取 / local 本地清单 / static 常用候选兜底 / none 无候选 */
export interface ModelDiscoverResult {
  ok: boolean;
  source: "remote" | "local" | "static" | "none";
  models: ModelOption[];
  error?: string | null;
}

/** 项目内已下载的本地模型（apps/api/models/） */
export interface LocalModelInfo {
  modelId: string;
  label: string;
  kind: string;
  repo: string;
  dimensions?: number | null;
  path: string;
  sizeMB: number;
  downloadedAt: string;
  desc: string;
}

export interface LocalModelList {
  modelsDir: string;
  downloadCommand: string;
  updatedAt: string;
  models: LocalModelInfo[];
}

export interface AuditEntry {
  at: string;
  actor: string;
  action: string;
  layer: string;
  detail: string;
}

/** 审计动作中文名：除「模型发现」外全部打点（与后端 AUDIT_ACTIONS 同构） */
export const AUDIT_ACTION_LABEL: Record<string, string> = {
  update_config: "修改配置",
  test_conn: "连通性自测",
  rollback_config: "版本回滚",
  migrate_model: "模型迁移",
};

/** 分层差异化参数的中文标签与输入类型（未收录的 key 直接展示原名、按文本处理） */
export const LLM_PARAM_META: Record<
  string,
  { label: string; kind: "number" | "text"; step?: number; min?: number; max?: number; hint?: string }
> = {
  temperature: { label: "温度", kind: "number", step: 0.1, min: 0, max: 2, hint: "出题建议 0.3~0.5，校验类建议 0" },
  maxTokens: { label: "最大 tokens", kind: "number", step: 256, min: 1 },
  timeoutSec: { label: "超时（秒）", kind: "number", step: 5, min: 1 },
  concurrency: { label: "并发上限", kind: "number", step: 1, min: 1, hint: "超出后排队，避免触发供应商限流" },
  dimensions: {
    label: "向量维度",
    kind: "number",
    step: 256,
    min: 1,
    hint: "变更后需重建 pgvector 索引",
  },
  sampleRate: { label: "采样率（Hz）", kind: "number", step: 1000, min: 1 },
  ttsVoice: { label: "面试官音色", kind: "text", hint: "语音层为下拉选择（Andre/Neil/Ethan 等）" },
  ttsModel: { label: "TTS 模型", kind: "text" },
  languageType: { label: "合成语种", kind: "text", hint: "与题目语种一致发音更准：Chinese / English / Auto" },
  speed: { label: "语速", kind: "number", step: 0.1, min: 0.5, max: 2 },
};

/* ---------------- 岗位检索（三期，引擎 B） ---------------- */

/** boss-agent-cli 探测结果（GET /api/jobs/status） */
export interface JobsStatus {
  cliInstalled: boolean;
  loggedIn: boolean;
  detail: string;
  /** 专用浏览器（CDP 9222）是否已连接；未连接时检索会 503，需先启动 */
  browserConnected?: boolean;
  /** 未连接时的启动指引（含命令） */
  browserHint?: string;
  /** 一键启动命令（启动脚本路径） */
  browserStartCommand?: string;
}

/** 启动 Boss 专用 Chrome 的结果（POST /api/jobs/browser/start） */
export interface BossBrowserStartResult {
  launched: boolean;
  reachable: boolean;
  chromeFound?: boolean;
  port?: number;
  chromePath?: string;
  profileDir?: string;
  startCommand?: string;
  detail?: string;
}

/** 岗位卡（后端已分层采样，采样后 ≤ 18 条） */
export interface JobCard {
  securityId: string;
  jobName: string;
  salary: string;
  brand: string;
  city: string;
  experience: string;
  education: string;
  skills: string[];
  industry: string;
  /** 岗位要求/职责描述片段（检索列表未必携带，为空时前端展开再拉全量 JD） */
  description: string;
  keyword: string;
}

/** 检索结果（POST /api/jobs/search） */
export interface JobSearchResult {
  keyword: string;
  city: string;
  jobs: JobCard[];
  dataSource: string;
  cached: boolean;
}

/** 岗位 JD 全量详情（GET /api/jobs/{securityId}/detail） */
export interface JobDetailResult {
  detail: Record<string, unknown>;
  dataSource: string;
  cached: boolean;
}

/** 考点地图报告（GET /api/jobs/map）：TOP 技能榜 + 三档考点分布 */
export interface JobMapSkill {
  name: string;
  ratio: number;
}

export interface JobMap {
  topSkills: JobMapSkill[];
  duties: string[];
  salaryInsight: string;
  tiers: { core: string[]; bonus: string[]; diff: string[] };
  degraded?: boolean;
  /** 两阶段漏斗产出的岗位匹配分（四期）：securityId -> {score 0~100, reason} */
  jobScores?: Record<string, { score: number; reason: string }>;
  /** Stage2 LLM 评分降级为词法分时为 true */
  scoreDegraded?: boolean;
  keyword: string;
  city?: string;
  dataSource?: string;
}

/* ---------------- 每日一练（三期） ---------------- */

/** 当日每日一练（GET /api/daily-practice，首次访问后端惰性生成 10 题） */
export interface DailyPractice {
  date: string;
  total: number;
  doneIds: string[];
  questions: Question[];
  streak: number;
  checkedInToday: boolean;
}

/** 完成进度上报结果（POST /api/daily-practice/progress；全部完成时打卡） */
export interface DailyProgressResult {
  doneCount: number;
  total: number;
  completed: boolean;
  checkedIn: boolean;
}

/* ---------------- 求职看板（四期，job_pipeline 四列状态机） ---------------- */

/** 看板阶段：已投递 / 笔试 / 面试 / Offer */
export type PipelineStage = "applied" | "written" | "interview" | "offer";

/** 岗位来源平台（zhipin 卡自动回填；其余为手动录入=能力边界降级） */
export type PipelinePlatform = "zhipin" | "zhilian" | "51job" | "liepin" | "manual";

/** 看板卡（GET/POST/PATCH /api/pipeline；practice 为挂接题集的练习进度） */
export interface PipelineCard {
  id: string;
  userId: string;
  stage: PipelineStage;
  securityId: string;
  keyword: string;
  jobName: string;
  brand: string;
  city: string;
  salary: string;
  platform: PipelinePlatform;
  /** 两阶段漏斗匹配分（0~100）；手动卡无分为 null */
  matchScore: number | null;
  /** 挂接的「岗位市场题集」id；无则空串 */
  setId: string;
  /** 面试日期（YYYY-MM-DD）；未设为空串 */
  interviewAt: string;
  note: string;
  inTrash: boolean;
  createdAt: string;
  practice: { done: number; total: number };
}

/** 趋势统计（GET /api/pipeline 的 stats） */
export interface PipelineStats {
  total: number;
  byStage: Record<PipelineStage, number>;
  newThisWeek: number;
  pendingInterview: number;
  avgMatchScore: number | null;
}

/** 四列看板（GET /api/pipeline） */
export interface PipelineBoard {
  columns: Record<PipelineStage, PipelineCard[]>;
  stats: PipelineStats;
  stages: PipelineStage[];
}

/** 加入看板入参：zhipin 卡传 securityId+keyword（自动回填）；手动卡传岗位字段 */
export interface PipelineAddInput {
  securityId?: string;
  keyword?: string;
  city?: string;
  jobName?: string;
  brand?: string;
  salary?: string;
  platform?: PipelinePlatform;
  note?: string;
  stage?: PipelineStage;
  interviewAt?: string;
}

/** 流转/编辑入参（PATCH /api/pipeline/{id}，字段均可选） */
export interface PipelinePatchInput {
  stage?: PipelineStage;
  note?: string;
  interviewAt?: string;
  setId?: string;
}

/* ---------------- 语音模拟面试（五期，文档 3.9） ---------------- */

/** 面试模式：技术 / 行为 / HR / 综合（决定出题维度侧重） */
export type InterviewMode = "tech" | "behavior" | "hr" | "mixed";

export const INTERVIEW_MODE_LABEL: Record<InterviewMode, string> = {
  tech: "技术面",
  behavior: "行为面",
  hr: "HR 面",
  mixed: "综合面",
};

export const INTERVIEW_MODE_HINT: Record<InterviewMode, string> = {
  tech: "系统设计、接口开发、性能与稳定性等技术深度问题",
  behavior: "以 STAR 法则考察项目经历、协作与问题解决",
  hr: "职业动机、稳定性、抗压与团队适配等软性问题",
  mixed: "技术 + 行为 + HR 混合，最贴近真实面试节奏",
};

/** 题目维度（与后端 generation 引擎 D 同构） */
export type InterviewDimension = "STAR" | "技术" | "HR";

/** 动态生成的开放式面试题（JSON 快照，不入题库） */
export interface InterviewQuestion {
  stem: string;
  dimension: InterviewDimension;
  keywords: string[];
  followUp: string;
  suggestSec: number;
}

/** STAR 四维评分（各维 0~10） */
export interface StarScores {
  situation: number;
  task: number;
  action: number;
  result: number;
}

/** STAR 四维中文标签（评分面板 / 雷达图共用） */
export const STAR_LABEL: Record<keyof StarScores, string> = {
  situation: "背景",
  task: "任务",
  action: "行动",
  result: "结果",
};

/** 单题作答结果（_answer_payload；submit 响应额外带 followUp） */
export interface InterviewAnswerResult {
  id: string;
  sessionId: string;
  seq: number;
  question: InterviewQuestion;
  transcript: string;
  starScores: StarScores | null;
  hitKeywords: string[];
  missedKeywords: string[];
  comment: string;
  durationSec: number;
  hasRecording: boolean;
  /** 触发的一层追问文本（submit 响应携带；无则 null） */
  followUp?: string | null;
}

/** 追问轮次（interview_turns） */
export interface InterviewTurn {
  turnNo: number;
  role: "interviewer" | "candidate";
  transcript: string;
}

/** 复盘报告（primary 层生成：四维雷达 + 总评 + 优势 + 改进建议） */
export interface InterviewReport {
  overall: number;
  radar: StarScores;
  summary: string;
  strengths: string[];
  improvements: string[];
}

/** 会话现场（创建 / GET /{id} 返回，含题目与已答明细） */
export interface InterviewSession {
  id: string;
  mode: InterviewMode;
  targetJob: string;
  questions: InterviewQuestion[];
  status: "running" | "finished";
  recordAudio: boolean;
  startedAt: string;
  finishedAt: string | null;
  total: number;
  answered: number;
  currentSeq: number;
  report: InterviewReport | null;
  answers: InterviewAnswerResult[];
}

/** 历史面试列表项（GET /api/interview-sessions） */
export interface InterviewListItem {
  id: string;
  mode: InterviewMode;
  targetJob: string;
  total: number;
  status: "running" | "finished";
  startedAt: string;
  finishedAt: string | null;
  hasReport: boolean;
}

/** 语音能力探测（GET /capabilities）：决定走录音还是降级文字、是否展示读题 */
export interface InterviewCapabilities {
  asrAvailable: boolean;
  ttsAvailable: boolean;
}

/** 复盘报告页数据（_report_payload：每题带追问轮次，开启留存时可回放录音） */
export interface InterviewReportAnswer extends InterviewAnswerResult {
  turns: InterviewTurn[];
}

export interface InterviewReportPayload {
  id: string;
  mode: InterviewMode;
  targetJob: string;
  status: "running" | "finished";
  total: number;
  answered: number;
  startedAt: string;
  finishedAt: string | null;
  report: InterviewReport | null;
  answers: InterviewReportAnswer[];
}
